- README.md
Hey friends! We are a startup in Beta and have build a connector using this great product called simplecov :+1: 
Thanks!
> Added codecov.io custom reporter

- lib/simplecov/configuration.rb
- lib/simplecov/source_file.rb
@sferik or anyone else on core.
Master build is currently red, this fixes it.
> Fix rubocop

- README.md
I think this gives the `README` a bit cleaner and more consistent look.
> Update badges to SVG versions

- CHANGELOG.md
Focussed on the user facing changes, hope I didn't miss any.
Ping @amatsuda as you did a lot of work on master recently :)
Decided to bump the minor, as there's also a feature and it's been some time since the last release :+1:
> Prepare Changelog for 0.13 release

- Rakefile
(note on PR style, I do lots of stuff as PRs so others have a chance to chime in but will eventually just merge it myself if I'm reasonably confident it's good - no need to feel pressured to merge/review :) )
> Running rubocop is fast --> faster failures if cop is broken

- Gemfile
- lib/simplecov/defaults.rb
- spec/result_merger_spec.rb
> Rubocop fix

- README.md
before:
https://github.com/colszowka/simplecov#contact
after:
https://github.com/pocke/simplecov/tree/fix-link-in-readme
> Fix a link to "Mailing List" in README.md

- README.md
> Bootsnap information in README

- CONTRIBUTING.md
- README.md
- spec/result_merger_spec.rb
Just fixing a pet peeve of mine.
> GitHub has a capital H

- CHANGELOG.md
This PR fixes a typo in the CHANGELOG.md.
> CHANGELOG.md typo fixed

- .travis.yml
https://github.com/rubygems/rubygems/issues/2055#issuecomment-357378260
follow up: #648
> Update ruby-version and remove cache to make it work again

- CHANGELOG.md
- simplecov.gemspec
docile's first release in 3.5 years!
There do not appear to be any breaking changes, according
to https://github.com/ms-ati/docile/blob/master/HISTORY.md
> Allow docile 1.2

- Gemfile
- benchmarks/result.rb
> Benchmark result generations statistics

- features/config_tracked_files_relevant_lines.feature
- features/step_definitions/simplecov_steps.rb
> Fixes the devils flaky

- .rubocop.yml
I just added the descriptions to help us understand the cops in an easier way.
> Add description to Rubocop cops

- .travis.yml
https://github.com/jruby/jruby/issues/5736
> Upgrade JRuby

- lib/simplecov.rb
Add new line to exit_status log.
> Add new line to exit_status log

- README.md
Add debian/ubuntu command for opening coverage file.
> add debian/ubuntu terminal cmd in README

- doc/alternate-formatters.md
Added to Alternate Formatters doc with the availability of simplecov-material
> Add Simplecov-Material Formatter availabilty

- .rubocop.yml
- Gemfile
- Gemfile.lock
- lib/simplecov.rb
- lib/simplecov/command_guesser.rb
- lib/simplecov/configuration.rb
- lib/simplecov/file_list.rb
- lib/simplecov/filter.rb
- lib/simplecov/formatter/multi_formatter.rb
- lib/simplecov/last_run.rb
- lib/simplecov/lines_classifier.rb
- lib/simplecov/profiles.rb
- lib/simplecov/result_merger.rb
- lib/simplecov/run_file_coverage.rb
- lib/simplecov/source_file.rb
- lib/simplecov/supports/branch_support.rb
- lib/simplecov/supports/source_file_support.rb
- lib/simplecov/useless_results_remover.rb
- spec/faked_project/lib/faked_project.rb
- spec/fixtures/frameworks/rspec_bad.rb
- spec/fixtures/frameworks/testunit_bad.rb
- spec/fixtures/resultset2.rb
> Upgrade and apply newest rubocop

- Gemfile
- Gemfile.lock
- features/branch_coverage.feature
- features/rspec_groups_and_filters_basic.feature
- features/step_definitions/html_steps.rb
- features/step_definitions/simplecov_steps.rb
- features/support/env.rb
- lib/simplecov/configuration.rb
- simplecov.gemspec
- spec/configuration_spec.rb
- spec/faked_project/Gemfile
#781 
Needs colszowka/simplecov-html/pull/74 which is a hint that we might wanna merge the repos :)
> Basic feature test for branch coverage

- Gemfile
- Gemfile.lock
- spec/fixtures/branch_tester_script.rb
- spec/fixtures/coverer.rb
- spec/source_file_spec.rb
> Add branch tester script test

- Gemfile
- Gemfile.lock
- features/branch_coverage.feature
- features/step_definitions/html_steps.rb
- features/support/env.rb
- lib/simplecov/source_file.rb
- spec/source_file_spec.rb
Some final pre release cucumber testing to make sure that incoming PRs with fixes don't break anything. Also some removal of unneeded methods and a bit nicer UI particularly in https://github.com/colszowka/simplecov-html/pull/77 / goes with that one.
#781
> Branch coverage feature test improvements

- Gemfile
- Gemfile.lock
- lib/simplecov/version.rb
Not yet released, just for good/meaningful dependency references
> Upgrade beta cycle reference

- .rubocop.yml
- Gemfile
- Rakefile
- features/step_definitions/html_steps.rb
- features/step_definitions/parameter_types.rb
- features/step_definitions/web_steps.rb
- lib/simplecov.rb
- lib/simplecov/combine/files_combiner.rb
- lib/simplecov/result.rb
- lib/simplecov/result_adapter.rb
- lib/simplecov/result_merger.rb
- lib/simplecov/simulate_coverage.rb
- lib/simplecov/source_file.rb
- spec/combine/results_combiner_spec.rb
- spec/configuration_spec.rb
- spec/file_list_spec.rb
- spec/result_merger_spec.rb
- spec/result_spec.rb
- spec/simplecov_spec.rb
- spec/source_file/branch_spec.rb
- spec/source_file_spec.rb
- spec/useless_results_remover_spec.rb
- test_projects/parallel_tests_project/Gemfile
It's not the highest impact change but since we dropped 1.8
there's no need for the hash rockets anymore and it was always
highly irritating to me
> Finally use Ruby 1.9 style hashes

- .github/workflows/stable.yml
At least that's what I think deivid meant :)
https://github.com/colszowka/simplecov/pull/848#issuecomment-580640435
> Try without installing jdk8 manually

- Gemfile
- Gemfile.lock
- features/branch_coverage.feature
- features/config_autoload.feature
- features/config_nocov_token.feature
- features/config_tracked_files.feature
- features/cucumber_basic.feature
- features/merging_test_unit_and_rspec.feature
- features/rspec_basic.feature
- features/rspec_groups_and_filters_basic.feature
- features/rspec_groups_and_filters_complex.feature
- features/rspec_groups_using_filter_class.feature
- features/skipping_code_blocks_manually.feature
- features/step_definitions/parallel_tests_steps.rb
- features/test_unit_basic.feature
- features/test_unit_collate.feature
- features/test_unit_groups_and_filters_basic.feature
- features/test_unit_groups_and_filters_complex.feature
- features/test_unit_groups_using_filter_class.feature
- features/unicode_compatiblity.feature
- test_projects/parallel_tests_project/Gemfile
As we started to force 2 digits after the dot for correct
alignment there the tests needed adjustments.
Makes me think more of merging the 2 repositories.
> Adjustments for the adjustment fixes of simplecov-html

- .gitignore
- features/cli_acceptance.feature
- test_projects/cli_acceptance/lib/cli_acceptance.rb
- test_projects/cli_acceptance/spec/app_spec.rb
- test_projects/cli_acceptance/spec/spec_helper.rb
The PR extends simplecov PR#859 with additional test code and specs, and adds (currently-disabled) code to reproduce simplecov issue #853, as requested by @PragTob.
> Cli acceptance testing test stub enhancements and #853 reproducability

- doc/alternate-formatters.md
Fix markdown formatting in docs.
> [docs] Fix simplecov-material link

- .github/workflows/stable.yml
> CI starting on push before opening a PR is nice with our matrix and run times

- features/support/env.rb
Whilst researching the issues in https://github.com/simplecov-ruby/simplecov/pull/927, I noticed the Capybara config could be simplified.
We can use [`Rack::Directory`](https://www.rubydoc.info/github/rack/rack/Rack/Directory) to serve the coverage report instead of providing a lambda.
> Use Rack::Directory to serve coverage report

- Gemfile.lock
- Rakefile
Flaky cukes have been bugging us. A lot, sadly. Yes they should
be fixed but they seem rather hard to fix/not straight forward/
easy and it's a pretty bad experience for new contributors to have
their stuff fail to begin with.
Hence, retrying is the pragmatic approach here.
> Begrudgingly default to a retry on cucumber tests

- README.md
> Clarify when to require simplecov for acceptance testing

- .github/workflows/stable.yml
According to the Internet this might or might not help.
> Maybe solve PR commits not running Actions

- CHANGELOG.md
- Gemfile.lock
- features/maximum_coverage_drop.feature
- lib/simplecov/exit_codes/maximum_coverage_drop_check.rb
- lib/simplecov/version.rb
- spec/exit_codes/maximum_coverage_drop_check_spec.rb
- spec/exit_codes/minimum_coverage_by_file_check_spec.rb
- spec/exit_codes/minimum_overall_coverage_check_spec.rb
> Maximum coverage drop fixes & moare exit code specs

- README.md
> Add earlier link to spring section

- .github/workflows/stable.yml
- Gemfile
- Gemfile.lock
> Use cache for bundler follow up

- .github/workflows/stable.yml
- .github/workflows/unstable.yml
Also updates checkout action version.
Runs green on my fork.
> Adds Ruby 3.2 to the CI matrix.

- .github/workflows/push_gem.yml
Let's see if this works :eyes: 
Hello from BalticRuby!
> Set up the trusted publisher together with @segiddins
