simplecov-ruby/simplecov

- README.md
It actually took me several hours to figure out why I wasn't getting the coverage I expected, granted that's because my test suite is slow and I'm new to SimpleCov, but I think this additional paragraph will save someone some time.
> Improve command name docs

- CHANGELOG.md
I hit the `at_exit` bug when running my suite on Travis CI with the [`codeclimate-test-reporter `](https://github.com/codeclimate/ruby-test-reporter) that (I think) manifested from the bug fixed in https://github.com/colszowka/simplecov/pull/302. The CHANGELOG as it currently stands made me think that the issue was never resolved as it pointed to #303! Pointing to the correct PR should appease/help desperate build fixers everywhere :smiley:!
> Fix mispointed link in CHANGELOG.md

- README.md
In this pull request i would like to add the supported text editors and plugins for simplecov to the README.
I recently developed a [Atom Editor](http://atom.io) Package which displays the simplecov results in a graphical layout.
I think thats its a good idea to list the supported text editors in the README. If you know more supported editors and plugins, please comment and i will add it in this pull request.
- [Atom Editor: coverage](github.com/philipgiuliani/coverage)
> [ci skip] Add editor support to the readme

- test/test_filters.rb
- test/test_result.rb
Some tests were changing global configuration settings
without restoring them afterwards. Fixes #362
> Fixes order dependencies in unit tests

- features/rspec_basic.feature
- features/rspec_groups_using_filter_class.feature
- lib/simplecov.rb
- lib/simplecov/defaults.rb
- test/faked_project/spec/forking_spec.rb
This handles the case where a test calls fork at some point, the new process shouldn't try to run coverage formatters or check the minimum coverage level.
This resolves #371.
> Only run the at_exit behaviors if the current PID matches the PID that called SimpleCov.start

- README.md
I hope the way I phrased everything is okay. As mentioned in issue #381 I set two configurations to `false` in my environment files. Such settings were also recommended by Rails. And although Spring preloads your environment, I find that still disabling `eager_load` helps Spring cooperate with SimpleCov
**ALSO** I know the contributing doc says to write tests for any changes, but since this is just the README, I do not think it is necessary. I can provide my own stats if needed (running my own suite).
```
DEPRECATION WARNING: The configuration option `config.serve_static_assets` has been renamed to
`config.serve_static_files` to clarify its role (it merely enables serving everything in the
`public` folder and is unrelated to the asset pipeline). The `serve_static_assets` alias will be …
```
> update README with Spring config

- CHANGELOG.md
- README.md
- features/rspec_groups_and_filters_complex.feature
- lib/simplecov/configuration.rb
- lib/simplecov/filter.rb
- test/test_filters.rb
- test/test_result.rb
After two years of waiting we finally can use arrays in simplecov groups
Thanks for the original PR #104 since the author did not respond after 2 years I decided to copy past the PR based on the master branch.
> Added feature from #104 allowing a array to be passed in a filter

- README.md
- lib/simplecov/defaults.rb
The Rails profile filters out `/vendor/bundle`, but this is also needed for many other kinds of Ruby projects.
A GitHub search illustrates how often developers need to configure this:
https://github.com/search?utf8=%E2%9C%93&q=simplecov+%22add_filter*vendor%22&type=Code&ref=searchresults
I can't think of any downside of having this as the default behaviour.
> Filter `/vendor/bundle` by default

- README.md
- lib/simplecov/configuration.rb
- lib/simplecov/defaults.rb
- lib/simplecov/file_list.rb
- lib/simplecov/result.rb
- spec/file_list_spec.rb
- spec/result_spec.rb
@ptashman I squashed and rebased, plus ghost wrote an extra sentence into the README.
If you're happy with this, I'll hit merge as soon as travis confirms green.
> Adds coverage calculation by individual file feature.

- Gemfile
- lib/simplecov/configuration.rb
As discussed at #400, simplecov features are currently broken, and that prevents some PRs unrelated to the failing features to get merged in.
This was caused by aruba's internal refactoring between 0.7 and 0.8 around [here](https://github.com/cucumber/aruba/blob/v0.8.1/lib/aruba/cucumber.rb#L339).
It seems like that `all be_...` is expected to to invoke RSpec's built in All matcher, but it actually calls Capybara's `page.all` in our context.
I would raise an issue for the aruba repo later, but let us lock the gem's version here until the problem is fixed there.
> Avoid bundling aruba 0.8.x for now

- lib/simplecov/defaults.rb
I wanted to add a test for this, but I couldn't get it working:
* on Ruby 2.2.2, rspec seg faults
* on Ruby 2.2.1 & 2.1.6, the feature (cucumber) tests have a lot of deprecations & failures e.g. 
```
The use of the "#before_cmd"-hook is deprecated. Please define with "#before(:command) {}" instead. Called by /Users/gerry/Dropbox/icc/simplecov/features/support/env.rb:47:in `block in <top (required)>'
Using the default profile...
The use of "in_current_dir" is deprecated. Use "#cd('.') { }" instead. Called by /Users/gerry/Dropbox/icc/simplecov/features/support/env.rb:37:in `block in <top (required)>'
...The use of "#set_env" is deprecated. Please use "set_environment_variable" instead. But be careful, this method uses a different kind of implementation. Called by …
```
> Fix default minimum coverage by file error message

- lib/simplecov/defaults.rb
```
Calculating -------------------------------------
start_with?   103.000  i/100ms
match    14.000  i/100ms
-------------------------------------------------
start_with?      1.043k (± 3.9%) i/s -      5.253k
match    147.419  (± 3.4%) i/s -    742.000
Comparison:
start_with?:     1042.7 i/s
match:      147.4 i/s - 7.07x slower
```
> speed up root_filter

- .rubocop.yml
- lib/simplecov/defaults.rb
This eliminates a Ruby :warning: when run with `RUBYOPT="-w"`.
You can easily reproduce the warning as follows:
`% ruby -w -rsimplecov -e 'SimpleCov.pid = Process.pid'`
> "warning: global variable `$ERROR_INFO' not initialized"

- features/step_definitions/transformers.rb
- features/support/env.rb
I was running tests and noticed there was a deprecation warning, as seen here:
https://travis-ci.org/colszowka/simplecov/jobs/78887751
Not sure if this will work in all the rubies, though. Let's see what travis has to say about that.
> Fixes deprecation warning in cucumber related to in_current_dir

- lib/simplecov/defaults.rb
The SimpleCov documentation states: "To avoid [duplicated configuration], you
can place a file called `.simplecov` in your project root." However, SimpleCov did
not actually look in the "project root" for this file, unless specially configured
to know where the project root is. Rather, it would simply look in the working
directory. Working directory != project root. (Unfortunately.)
Therefore, when looking for `.simplecov`, recurse upwards from the working directory
until it is found (or the root directory is reached). This is comparable to the
way that git recurses upwards looking for a .git directory, meaning that you can
use git anywhere in your project root or below.
Since there is no guarantee that you have permissions to read `.simplecov`, catch
exceptions and display a warning …
> Recurse upward looking for .simplecov

- features/config_tracked_files.feature
- lib/simplecov.rb
- lib/simplecov/configuration.rb
- lib/simplecov/defaults.rb
- spec/faked_project/lib/faked_project.rb
- spec/faked_project/lib/faked_project/untested_class.rb
Fixes #413 
Added a configuration option `track_files` that accepts
a glob. With this enabled, coverage result will include
uncovered files that match the glob.
In the `rails` profile this is set to `{app,lib}/**/*.rb`
Regarding line count issue:
It is not easy to determine which lines should be classified as relevant (this is done by the ruby parser), so this implementation does not touch the coverage information for covered files, to avoid ruining the accurate percentages.
When handling uncovered files it uses an approximation function to determine if the line is relevant or not, based on the code present in #16. As uncovered files have 0% coverage, this will only affect the global percentage, so I don't think it's an issue.
> Adds option to track uncovered source files.

- CHANGELOG.md
- Gemfile
- lib/simplecov/version.rb
- spec/filters_spec.rb
- spec/helper.rb
- spec/result_spec.rb
@colszowka @sferik @amatsuda 
cc @ptashman @raszi we're releasing your changes!
I'll tag v0.11.0 after merging then push to rubygems.
> Bump to 0.11.0, with Changelog.

- CHANGELOG.md
Modify "changes" link in `CHANGELOG.md` to point to right compare page: https://github.com/colszowka/simplecov/compare/v0.10.0...v0.11.0
> Modify changes link between 0.10.0 and 0.11.0

- lib/simplecov.rb
This also rewords the warning to hint at the user the multiple ways to do things
so they can choose what fits them the best, maybe even creating a .jrubyrc file or
using `-d` or `-X` any of the known ways.
> Fix #420: Use JRuby.runtime so the user can use all JRuby debug ways.

- lib/simplecov/merge_helpers.rb
- lib/simplecov/result.rb
- spec/merge_helpers_spec.rb
Requiring simlpecov globally adds the `merge_resultset` method to the built-in Array class and Hash class via monkey-patching, which means this gem widely changes the test subject's behavior.
Such a horrible vandalism should never be done by a test coverage measurement tool. We should immediately stop doing this.
I suppose the same merging logic could be more safely and cleanly implemented by two or three static methods instead of extending the core classes, but for now, I'd suggest a patch that changes the Result class to dynamically extend the result objects using the existing Modules.
This way we would be able to minimize the conflict with other PRs working on the merging_helpers e.g. #436 and #441.
> Stop polluting ::Array and ::Hash

- .rubocop.yml
- Gemfile
- lib/simplecov.rb
- lib/simplecov/configuration.rb
- lib/simplecov/defaults.rb
- lib/simplecov/jruby_fix.rb
- lib/simplecov/result.rb
- lib/simplecov/source_file.rb
- lib/simplecov/version.rb
- spec/source_file_spec.rb
This brings it up-to-date for `v0.36.0`.
Changelog: https://github.com/bbatsov/rubocop/blob/master/CHANGELOG.md#0360-14012016
> Make compatible with latest RuboCop

- lib/simplecov.rb
- lib/simplecov/configuration.rb
> Silence `@track_files_glob` ivar warning

- lib/simplecov/configuration.rb
This is to avoid calling `FileUtils.mkdir_p` like 50 times, like visible here when `$DEBUG = true`:
```
[...]
Finished in 0.20738 seconds (files took 0.69467 seconds to load)
42 examples, 1 failure, 1 pending
Exception `Errno::EEXIST' at /Users/paddor/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /Users/paddor/src/ruby/cztop/coverage
Exception `Errno::EEXIST' at /Users/paddor/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /Users/paddor/src/ruby/cztop/coverage
Exception `Errno::EEXIST' at /Users/paddor/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /Users/paddor/src/ruby/cztop/coverage
Exception `Errno::EEXIST' at /Users/paddor/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:253 - File …
```
> memoize SimpleCov::Configuration#coverage_path

- lib/simplecov/defaults.rb
I'm using Active Job in a Rails project for the first time and my job classes are currently "Ungrouped". Since `app/jobs` is the default location for these classes, I think it's worth adding this to the Rails profile.
Are there tests for this? I couldn't find any but if I've missed them, please point them out and I'll add a test as well. Thanks
> add a group for Active Jobs classes to default Rails profile

- lib/simplecov/defaults.rb
If SimpleCov.root is set to other directory, but root_filter uses current directory.
```ruby
require 'simplecov'
SimpleCov.root '/other/directory'
obj = Struct.new(:filename).new('/other/directory/test.rb')
p SimpleCov.filters.any?{ |filter| filter.matches? obj }
#=> returns true but it should be false.
```
> Fix root_filter evaluates SimpleCov.root before initialization.

- .rubocop.yml
- lib/simplecov/version.rb
Older versions of rubygems choke on an immutable version string.
I wasn't able to actually get rubocop to complain about the mutable constant so I couldn't verify that the second commit actually does anything.
> Unfreeze SimpleCov::VERSION

- Gemfile
> Limit rake version to 10.x for Ruby 1.8.7

- lib/simplecov.rb
`JRuby.runtime.debug?` does not answer correctly wether coverage is active for JRuby.  `org.jruby.RubyInstanceConfig.FULL_TRACE_ENABLED` does.
Enabling general debug mode on JRuby does not enable coverage.  You need the "--debug" flag on the command line or in JRUBY_OPTS, or set the "debug.fullTrace=true" option in ".jrubyrc".
This change should make using simplecov on JRuby a bit nicer.
> Correct the detection and guide for JRuby coverage

- spec/faked_project/spec/forking_spec.rb
This fixes 10 test failures for JRuby in travis
> Avoid forking test for JRuby since fork is not implemented

- features/support/env.rb
`--dev` sets useful options for faster startup and better performance for short-running apps, including -X-C
`--debug` is necessary on JRuby 9K to get coverage at all
`--1.9` is default for JRuby 1.7.x and not recognized on JRuby 9K
> Set useful JRUBY_OPTS

- README.md
The proposed change removes the section about Riot from the readme, RIot hasn't been touched for over 2 years, and the author has [abandoned the gem](https://github.com/thumblemonks/riot/issues/52).
> Removed riot from the readme

- lib/simplecov/merge_helpers.rb
- spec/merge_helpers_spec.rb
The coverage rate has decreased when used with `parallel_tests`. So, I fixed it.
This Pull Request is to change behaviors of 2 and 4.
| no | element | new_array[i] | before | after |
|----|----|----|----|----|
| 1 | nil | nil | nil | nil |
| 2 | nil | 0   | 0   | **nil** |
| 3 | nil | 1   | 1   | 1 |
| 4 | 0   | nil | 0   | **nil** |
| 5 | 0   | 0   | 0   | 0 |
| 6 | 0   | 1   | 1   | 1 |
| 7 | 1   | nil | 1   | 1 |
| 8 | 1   | 0   | 1   | 1 |
| 9 | 1   | 1   | 2   | 2 |
- Ruby 2.2.3
- Rails 4.2.5
- simplecov 0.11.1
- parallel_tests 1.7.0
> Fix coverage rate of the parallel_tests

- spec/return_codes_spec.rb
> use around

- lib/simplecov/merge_helpers.rb
- spec/merge_helpers_spec.rb
reopens #506 
- Merging `{file => [nil, 0, 1]}` and `{}` results in `{file => [nil, 0, 1]}` (ok)
- Merging `{}` and `{file => [nil, 0, 1]}` results in `{file => [nil, nil, 1]}` (0 is lost, this is the bug)
When merging two result sets, if a file is missing on the LHS, which means the file is not loaded, zeros for the file on the RHS will be lost.
> Fix merging of result sets for unloaded files

- lib/simplecov/result.rb
I (accidentally ⏤ Homebrew/brew#1041) loaded a very large number of files into SimpleCov, and it got stuck for a very long time. I tracked down the slowness to this method, which gets very slow because it iterates `filenames` for every value of `original_result`. Using Ruby's built-in `Array#&` makes this much faster.
> Fix an accidentally inefficient hash filter

- lib/simplecov/configuration.rb
- lib/simplecov/source_file.rb
The range of `Fixnum` is not guaranteed at all.  And ruby 2.4
unifies `Fixnum` and `Bignum` into `Integer`, and will deprecate
those two constants.
> Use Integer instead of Fixnum

- .travis.yml
I thought it'd be worth running against the current JRuby release, not just head. I didn't want to interfere with a support decision (although I'd love to see JRuby officially supported!) so added it to the allow_failures for now. Thanks for the great work, long time simplecov user :) (and with that also the whole shoes4 project on JRuby) !
> Test current JRuby release

- lib/simplecov/source_file.rb
Before this commit all source code were loaded, even if
they are not used.
For example when taking test coverage for rails applications,
in many cases files on "vendor/bundle" are filtered out.
By reading source code lazily, the time required to generate
results will be shortened.
> Stop to read unused source code

- .travis.yml
- README.md
I've personally been running simplecov with JRuby 1.7+ for years
so I'd say it is good to go either way ;P
The reality of edge cases is more complicated but it seems the
fine folks at @jruby (namely @enebo ) made the last fixes
necessary as seen in jruby/jruby#1196 so that they're available
in 9.1+ releases! The others should work, but have some little
failures (9.0.5.0 fails on one cuke for me).
So, the easiest way forward is to support 9.1+. Sadly the tests
take a while as they always start new interpreter instances and
startup time isn't exactly JRuby's strength, but CI does it
so it's bearable. :)
If anyone has problems with JRuby on a PR, in an issue or whatever
please feel free to ping me (@PragTob)
Also, special thanks goes to @donv who created did a lot of testing,
issue reporting …
> Officially Support JRuby 9.1+

- .travis.yml
Keen eyes might have observed that in #547 while reformatting the
section about supported rubies I also removed the mention of
Rubinius. I did this as it said they were just tested to make sure
they don't crash which wasn't true anymore - full test suite is run
but it was set to allowed failures.
Sadly Rubinius hasn't been running/installing at all on travis for
quite some time: https://travis-ci.org/colszowka/simplecov/jobs/169209429
And before when it was still running it was failing on a lot of
cukes: https://travis-ci.org/colszowka/simplecov/jobs/141918713
As tests don't run/no one looks at aren't worth much I'm inclined
to drop it from the test matrix, plus my recent experience with
getting it running hasn't been stellar.
We might always readd once they get their new interpreter and …
> Remove Rubinius/rbx from the test matrix

- features/config_nocov_token.feature
- features/skipping_code_blocks_manually.feature
- lib/simplecov/source_file.rb
- spec/file_list_spec.rb
- spec/source_file_spec.rb
When using the `nocov` comment token the start and stop tokens are considered lines to be covered. Addresses the following issues:
colszowka#468
colszowka#527
> Skip the :nocov: comments.

- CHANGELOG.md
- lib/simplecov/last_run.rb
- spec/last_run_spec.rb
I took the liberty to merge the #533 of @cshaffer to resolve the merge conflict. Sorry that it took some time!
Original text:
> Fixes #410 
> When running tests in parallel using [parallel_tests](https://github.com/grosser/parallel_tests) and [parallel_tests-fine_grain_test](https://github.com/appfolio/parallel_tests-fine_grain_test) sometimes one thread will be completely starved from running any tests which results in an empty last_run json file which blows up when collecting all the results.  This PR makes it so we don't try to parse an empty string as json and instead return `nil` as if the file wasn't there at all.
> 
> Since there were no tests for `SimpleCov::LastRun` I took the liberty of writing tests for everything including the change I made.
> Allow for empty last_run files for parallel tests by cschaffer

- README.md
environment: 
* ruby: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
* rails: 5.0.0.1
* simplecov (0.12.0)
when running `rails server`, you'll get the warning:
> DEPRECATION WARNING: `config.serve_static_files` is deprecated and will be removed in Rails 5.1.
Please use `config.public_file_server.enabled = false` instead.
[rails line of code for the deprecation](https://github.com/rails/rails/blob/69ab3eb57e8387b0dd9d672b5e8d9185395baa03/railties/lib/rails/application/configuration.rb#L70)
> [ci skip] Update config for using with spring

- README.md
“i.e.” means “that is” or “in other words” and is mean to clarify, whereas “e.g.” means “for example”, which is what these instances in the documentation are providing (i.e., examples) :)
> Use e.g. instead of i.e.

- CHANGELOG.md
- features/maximum_coverage_drop.feature
- features/refuse_coverage_drop.feature
- lib/simplecov/configuration.rb
- lib/simplecov/defaults.rb
Rebased/slightly cut reopen of #469 by @Miloshes
Original text:
> Refuse_coverage_drop option is great but if the coverage actually dropped, it will only fail your test suite once. The .last_run.json file gets overwritten and tests are passing again.
>
> Proposed changes look for "refuse_coverage_drop" option and if it is enabled, prevent overriding of the file when the coverage has dropped.
> Don't overwrite last_run file if refuse_coverage_drop option is enabled and the coverage has dropped 

- spec/helper.rb
- spec/support/fail_rspec_on_ruby_warning.rb
Originally stolen from: https://github.com/metricfu/metric_fu/blob/master/spec/capture_warnings.rb
Heavily modified though - e.g. put into a class, using stringio,
removed the bundler directory as not used here and moved to
before the before of the rspec suite to also capture parse time
warning errors.
Replaces #457 ( cc @bf4 @fornellas ) - basically decided for this as it doesn't mess with `Kernel.warn` and is able to capture more, even rearranged it so that it catches parse time errors :tada: 
As this is some functionality I've wanted for a long time, I heavily consider extracting this and making it a small little gem that could then also play with Cucumber/Minitest and friends :)
> Fails specs on ruby warnings

- CHANGELOG.md
- lib/simplecov/version.rb
All outstanding PRs were closed and among them are some neat bugfixes and features, sounds like a nice thing to release to everyone.
What do you think? @colszowka @bf4 
------------------------------------------
* Officially support JRuby 9.1+ going forward (should also work with previous releases). See [#547](https://github.com/colszowka/simplecov/pull/547) (ping @PragTob when encountering issues)
* Add Channel group to Rails profile, when `ActionCable` is loaded. See [#492](https://github.com/colszowka/simplecov/pull/492) (thanks @BenMorganIO)
* Stop `extend`ing instances of `Array` and `Hash` during merging results avoiding problems frozen results while manually merging results. See [#558](https://github.com/colszowka/simplecov/pull/558) (thanks @aroben)
* Fix parallel_tests when a …
> 0.14.0 release?

- CHANGELOG.md
- lib/simplecov/source_file.rb
- spec/fixtures/never.rb
- spec/fixtures/skipped.rb
- spec/fixtures/skipped_and_executed.rb
- spec/source_file_spec.rb
* Fixes #563 hopefully
* tracked the bug back to hopefully b35f569fdb79f1175 (only thing
that touched the caller of the method, but maybe there is some
other interaction ongoing)
* Guess is/was that this might trigger if there aren't any lines
covered... obviously test cases still missing to up our
coverage here :)
> Try at fixing FloatDomainError more closely restoring origin version

- .rubocop.yml
- lib/simplecov/defaults.rb
Thank you for your nice gem.
I found that latest travis-ci failed due to rubocop offense errors.
This is caused by updating rubocop version to v0.48.0.
There are 3 kinds of errors.
1. Sytle/InverseMethods
2. Style/SymbolArray
3. Style/IndentHeredoc
I fixed these errors as follows. Please check my PR.
Thanks.
```
lib/simplecov/defaults.rb:10:5: C: Use !~ instead of inverting =~.
!(src.filename =~ root_filter)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
This cop is added on v0.48.0 by [this PR](https://github.com/bbatsov/rubocop/pull/4000).
I fixed this offense by using `!~` instead of invering the result of `=~`.
```
Rakefile:37:22: C: Use %i or %I for an array of symbols.
task :default => [:spec, :cucumber]
^^^^^^^^^^^^^^^^^^
Rakefile:39:22: C: Use %i or %I …
```
> Fix rubocop errors

- lib/simplecov/file_list.rb
In certain cases I get an error for inject(&:+) however things work fine for inject(:+) and sum. This change to use inject(:+) seems to solve it for me across ruby versions whereas sum fails on older rubies. Otherwise have to use a monkeypatched version which is a bit of a shame :(
> switch inject to sum

- .travis.yml
http://jruby.org/2017/05/16/jruby-9-1-9-0.html
There is `NoMethodError: undefined method `status' for #<Array:0x47c4ecdc>` error reported at CI with jruby-head. This error may reproduce with Ruby 9.1.9.0.
> CI agains jruby-9.1.9.0

- README.md
- doc/editor-integration.md
- lib/simplecov/configuration.rb
- lib/simplecov/defaults.rb
- lib/simplecov/filter.rb
- lib/simplecov/source_file.rb
- spec/filters_spec.rb
- spec/source_file_spec.rb
Add the ability to use regex filters. The regexes should match against the files path relative to the current project, not the full path to root. For example, the file /Users/jon/project/app/foo/test.rb would match on a filter of "jon". I made the String and Array matchers follow that new rule as well.
Fixes #514
> Add regex filters

- lib/simplecov/formatter/simple_formatter.rb
- lib/simplecov/version.rb
These changes ensure that all string literals can be frozen (as per the optional feature in MRI 2.3 and onwards).
I would recommend adding the following to your .travis.yml file to ensure regressions aren't introduced:
```yml
before_script:
- if (ruby -e "exit RUBY_VERSION.to_f >= 2.4"); then export RUBYOPT="--enable-frozen-string-literal"; fi; echo $RUBYOPT
```
This will add the flag when the tests are run on MRI 2.4 or newer (while the feature was introduced in 2.3, it doesn't seem to work reliably until 2.4). However, at this point in time for the tests to pass, you'll need to use the latest RSpec commits, along with submitted patches to simplecov-html, test-unit, and parser (for rubocop):
* https://github.com/colszowka/simplecov-html/pull/56
* …
> Allow library to be used with frozen-string-literals enabled.

- README.md
The README contains a typo in code example, where `fales` should be `false`.
> Fix small "fales" typo in array filter section of README

- lib/simplecov.rb
- lib/simplecov/result_merger.rb
- spec/result_merger_spec.rb
- spec/simplecov_spec.rb
Ensure we cache appropriately so we don't merge more than once or do unsafe reads of the resultset.
See https://gist.github.com/jenseng/62465f674f8c02de09ef776f23d4dca4 for simple repro script.
Fixes #406 and may partially address #559 (though enforcing covered_percentage still requires workarounds à la [this comment](https://github.com/colszowka/simplecov/issues/559#issuecomment-280805651), since any process before the last one won't have all the coverage data)
Basically there are 3 main problems when using merging:
1. `SimpleCov.result` doesn't cache the `@result`, so the default `at_exit` behavior causes it to store and merge 3 times.
2. `SimpleCov::ResultMerger.resultset` calls `.stored_data` twice.
3. `SimpleCov::ResultMerger.merged_result` doesn't synchronize or use a cached …
> Fix merging race conditions

- README.md
Seems like a simple typo in the README linked both the Spring and Bootsnap "see section below" link tot he Spring explanation.
> Link Bootsnap in README to the right anchor

- features/config_tracked_files.feature
- features/config_tracked_files_relevant_lines.feature
- lib/simplecov.rb
- lib/simplecov/lines_classifier.rb
- lib/simplecov/source_file.rb
- spec/lines_classifier_spec.rb
As discussed in #604, unloaded files appear to have whitespace, comments & nocov block lines counted as relevant. This leads to the overall coverage being understated.
> Fix relevant lines for unloaded files

- doc/alternate-formatters.md
This formatter is used to emulate t_wada AA (not exact though).
- t_wada is Japanese famous TDD practitioner
- actual AA is like [this](http://twitpic.com/dzgwk8)
thanks :)
> Add another SimpleCov formatter

- lib/simplecov/defaults.rb
- spec/filters_spec.rb
Given project directory `/foo/app` and BUNDLE_PATH `/foo/app_cache`,
ensure the latter is filtered out correctly by the default root filter,
since it's outside of SimpleCov.root.
Otherwise you'll see all those gem files in your coverage report, with
nonsensical paths like `._cache/ruby/2.4.0/gems...`, unless you add a
nonsensical `/^_cache/` filter
Also add some test coverage for the default filters
> Filter directories outside SimpleCov.root that have it as a prefix

- lib/simplecov/defaults.rb
- spec/defaults_spec.rb
- spec/filters_spec.rb
In converting this to a regex in a0b14a1, an extra leading `/` was added,
making this filter less useful (it would literally match the `/^/db/`
path).
> Fix regression in rails filters

- ISSUE_TEMPLATE.md
- README.md
Have had a few too many issues lately that were resolved by just
requiring and starting simplecov first. It's already pretty clear
in the README but I thought meh, might as well go the extra mile.
* Put it up in another trouble shooting section
* also include the fancy rails_helper name in there
* Include a little trick that has helped me debug this issue with
users
* Add issue template based on CONTRIBUTING to raise awareness
* adjust CONTRIBUTING a bit to bring up the whole require first
part a bit more
> Make it even clearer that simplecov absolutely needs to start first

- .rubocop.yml
- Gemfile
> Rubocop doesn't exclude .files for **/* --> workaround

- features/maximum_coverage_drop.feature
- lib/simplecov/defaults.rb
Fixes #624 
Just taking out the max coverage drop check outside the success if statement. I can't think of a reason to leave it in the success if statement, but of course I am not too familiar with this codebase :) . Can you think of a reason why we would want to write to ```.last_run.json``` on failing tests?
The only thing that I wasn't sure of is, if a test is failing, maybe we want to leave the pre-existing non-zero exit status rather than writing an exit status of 3.
> Fixes #624 Checks max_coverage_drop on failed tests

- lib/simplecov/defaults.rb
- lib/simplecov/profiles/bundler_filter.rb
- lib/simplecov/profiles/rails.rb
- lib/simplecov/profiles/root_filter.rb
- lib/simplecov/profiles/test_frameworks.rb
The goal behind this PR is to simplify the ```defaults.rb``` file. It
just breaks out the default profiles into their own files to
reduce the noise in this ```defaults.rb``` file
Things I like about this PR:
- It simplifies ```defaults.rb```
- It gives structure to any more default profiles that will be added, or
other default files to be added.
Things I don't like about this PR:
- Typically folders are used for namespacing and the ```defaults/``` folder
is not used in that way in the PR.
- There will probably be very few if any more default profiles added, so
point 2 above has little weight.
- The files inside```defaults/``` actually sets up default profiles, so
maybe we should use a ```profiles/``` folder? or ```default_profiles/```
folder? Although a ```default/``` folder is generic …
> Break default profiles out into new files

- lib/simplecov/filter.rb
- spec/filters_spec.rb
Previously, filter strings passed to `add_filter` have been handled as regexps. It means, for example, `add_filter '.pl'` matches against `sample.rb` because `.` is handled as _any character_ in regexp.
As now we have [regexp filter](#589), there's no reason to handle filter strings as regexps.
However we need to think about semver with this change. If this behavior was intentional, we cannot introduce this change until next major version bump. Or we can do if this was a _bug_.
What do you think?
> Stop handling string filters as regexps

- lib/simplecov.rb
- lib/simplecov/defaults.rb
- spec/simplecov_spec.rb
Fixes #493
This stores any exit exception that may have occurred. The idea is to
expose this exception to the user supplied ```at_exit``` block.
```ruby
SimpleCov.at_exit do
if SimpleCov.exit_exception
else
end
end
```
Another method was added: ```exit_status_from_exception``` to reduce the
logic in the at_exit block. I am not sure if it's worth adding this
method though. There is still opportunity to refactor the ```at_exit```
block. I first attempted to refactor the @exit_status logic more but
it will be a bigger change. If you want I can remove the
```exit_status_from_exception``` method from this PR
I also don't love having ```begin rescue end``` blocks in tests, but I wasn't sure
if there was a better way to test that. Maybe I could wrap ```$!/$ERROR_INFO```
in another method and …
> Fixes #493 Capture exit exception for reference

- lib/simplecov/profiles/rails.rb
In my project I have the following file : app/controller/mercadolibre/users_controller.rb
It is wrongly recognized as a Library file.
Workaround while this PR get merged:
```ruby
SimpleCov.start 'rails' do
add_group 'Libraries', 'lib/'
end
```
> Only filter files in lib folder

- simplecov.gemspec
This PR excludes the `cucumber.yml` configuration file from the gem.
See https://github.com/cucumber/cucumber-rails/issues/346#issuecomment-361167227
> gemspec: Avoid distributing cucumber.yml

- .rubocop.yml
- lib/simplecov.rb
- lib/simplecov/defaults.rb
I extracted a SimpleCov.process_result method from the at_exit block in defaults.rb
I originally used this to decouple the SimpleCov run from report generation, so
that I can merge reports.
See an example of this at
- https://github.com/rails-api/active_model_serializers/blob/13340790c5c162718a6a4fe2f8aa542f8ec3b23e/scripts/coverage_report.rb#L51-L80
- https://github.com/rails-api/active_model_serializers/blob/13340790c5c162718a6a4fe2f8aa542f8ec3b23e/.simplecov#L31-L48
pasted below for convenience
`.simplecov`
```ruby
ENV['FULL_BUILD'] ||= ENV['CI']
SimpleCov.profiles.define 'app' do
coverage_dir 'coverage'
load_profile 'test_frameworks'
add_group 'Libraries', 'lib'
add_group 'Long files' do |src_file|
src_file.lines.count > 100
end
class MaxLinesFilter < SimpleCov::Filter
def …
```
> Refactor at_exit process result

- doc/alternate-formatters.md
I needed to generate output from simplecov that displayed in the output of my CI jobs. I implemented this via a user-configurable ERB template, so that the output format can be customized with minimal friction. Source is at https://github.com/kpaulisse/simplecov-erb and it's available under the MIT license.
> Update alternate-formatters.md with simplecov-erb

- CONTRIBUTING.md
The doc said simplecov uses Test::Unit but it uses RSpec and Cucumber.
Updated the doc to be correct, and fixed the examples of how to run
tests.
> Update the CONTRIBUTING doc.

- CHANGELOG.md
- lib/simplecov/lines_classifier.rb
In my measurements the majority of the time in SimpleCov was being
spent in this one-line function.
In my tests on a large project at Airbnb, this change makes SimpleCov run
from **2.5x to 3.75x faster** when processing results. 
(From 154.2 seconds down to 60.6 seconds in one test. 
From 16.6 seconds down to 4.4 seconds in another.)
Admittedly, memoizing it does change its behavior but only in the edge
case where someone runs SimpleCov twice in a single test run, changing
the +nocov_token+ between the two runs. This is such an odd edge case I
decided not to worry about it.
> Performance: memomize LinesClassifier::no_cov_line

- Gemfile
- simplecov.gemspec
- spec/helper.rb
- Ruby 1.9.3 could not bundle install because it complained about frozen
strings RUBY_VERSION and SimpleCov::VERSION. Calling `dup` returns
an unfrozen string.
- Tests weren't passing in any Ruby version because `require "stringio"`
was happening too late. This resulted in:
```
Failure/Error: @stderr_stream = StringIO.new
NameError:
uninitialized constant FailOnWarnings::StringIO
./spec/support/fail_rspec_on_ruby_warning.rb:9:in `initialize'
```
> Make tests pass.

- README.md
In my Rails 5 app, 
`config.public_file_server.enabled = false` 
setting will make all UI tests (RSpec System spec) fail.
I believe that static asset server setting has nothing to do with Spring and SimpleCov.
`config.eager_load = false` is just enough.
For the same reason, for Rails 4 we may not need to set
`config.serve_static_files = false`
but I haven't checked it.
> Static asset server setting has nothing to do

- CHANGELOG.md
- lib/simplecov/lines_classifier.rb
It's even a tiny bit faster it seems.
```
Memoization:
tobi@speedy ~/github/simplecov $ bundle exec ruby benchmarks/result.rb
Warming up --------------------------------------
generating a simplecov result
28.000  i/100ms
Calculating -------------------------------------
generating a simplecov result
282.997  (± 1.4%) i/s -      1.428k in   5.047055s
Modifier:
tobi@speedy ~/github/simplecov $ bundle exec ruby benchmarks/result.rb
Warming up --------------------------------------
generating a simplecov result
28.000  i/100ms
Calculating -------------------------------------
generating a simplecov result
289.115  (± 1.7%) i/s -      1.456k in   5.037437s
```
> TIL there is an `o` modifier doing the same thanks to @eregon

- CHANGELOG.md
- lib/simplecov/lines_classifier.rb
- lib/simplecov/source_file.rb
- spec/lines_classifier_spec.rb
This is an improvement on #664, which fixes SimpleCov so it won't crash when it encounters an invalid byte sequence in UTF-8.
This version is better in these ways:
1. The `classify` method is still short enough to make Rubocop happy.
2. The code that ignores invalid byte sequences is reused in the two places where we iterate over all the lines looking for `:nocov:`: `SimpleCov::LinesClassifier#classify` and `SimpleCov::SourceFile.process_skipped_lines`.
Like #664, this fixes a regression that was introduced in v0.15.0 when `add_not_loaded_files` was changed to call `LinesClassifier#classify`, which runs a RegExp on each line--and raises ArgumentError if the line had an invalid byte sequence.
> Ignore invalid byte sequences

- README.md
A cleaner solution to usage with spring than copying `SimpleCov.start` code to `config/spring.rb`. 🍝 
According to suggestion from @ibrahima here https://github.com/colszowka/simplecov/issues/381#issuecomment-347651728
and @adampope here https://stormconsultancy.co.uk/blog/development/ruby-on-rails/getting-accurate-code-coverage-metrics-from-simplecov-rails-project/
I took a chance and removed the current instruction because I felt it wasn't as good, but I'll gladly add it back if you feel that both should be there. 😇
I'm not sure if there are any cons to calling eager load here so it would be good to hear from more people if this is a good solution. 📣
For my rails project I got 0% coverage until I copied `SimpleCov.start if Rails.env.test?` into `config/spring.rb`, then I looked around …
> Update instuctions for usage with spring to suggest Rails.application.eager_load!

- .travis.yml
- Gemfile
- gemfiles/jruby.gemfile
- gemfiles/ruby_18.gemfile
- gemfiles/ruby_19.gemfile
- gemfiles/ruby_20.gemfile
- gemfiles/ruby_21.gemfile
- gemfiles/ruby_22.gemfile
- gemfiles/ruby_23.gemfile
- gemfiles/ruby_24.gemfile
- gemfiles/ruby_25.gemfile
- gemfiles/ruby_trunk.gemfile
- simplecov.gemspec
We can not specify "trunk" for `#platforms` of Gemfile, so we can not run CI with "ruby-head".
This PR separates each gemfiles to 'gemfiles/*.gemfile'. We can specify arbitrary gem versions by this change.
> Fix CI for ruby-head to be run

- gemfiles/jruby.gemfile
- gemfiles/ruby_19.gemfile
- gemfiles/ruby_20.gemfile
- gemfiles/ruby_21.gemfile
- gemfiles/ruby_22.gemfile
This PR restores https://github.com/colszowka/simplecov/commit/0d2fe5b543060335fb6f234421d7a21e45ea98f1, with a small modification: specify `development_group: 'test'` as an argument to `gemspec`, so that it works properly on TravisCI.
> No need to explicitly bundle gems included in the gemspec

- .travis.yml
This PR only updates the CI matrix to the latest generally available Ruby versions.
Source for version numbers: https://github.com/rvm/rvm/blob/master/config/known
> CI: Use 2.4.6, 2.5.5, 2.6.2, jruby-9.2.6.0

- .travis.yml
Removes an old setting from Travis. See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
I marked this as CI skip - perhaps that's not how to do it, in this project, but the setting "does nothing", now.
> CI: Drop unused Travis option

- .travis.yml
This PR only updates the CI matrix to the latest generally available Ruby versions.
Source for version numbers: https://github.com/rvm/rvm/blob/master/config/known
> CI: Use 2.6.3, jruby-9.2.7.0

- lib/simplecov/source_file.rb
- spec/source_file_spec.rb
I was configuring simplecov in bundler's specs and I got this crash in one of the specs:
```
/home/travis/build/bundler/bundler/tmp/gems/base/gems/simplecov-0.16.1/lib/simplecov/source_file.rb:87:in `project_filename': empty char-class: /^\/home\/travis\/build\/bundler\/bundler\/tmp\/foo[]bar/ (RegexpError)
```
This PR should fix that super-edge case.
> Support project roots with special characters

- lib/simplecov.rb
- spec/result_merger_spec.rb
Encountered in infertux/bashcov#36.
In the following snippet, `SimpleCov.process_result` is called with `SimpleCov.result` as the first parameter.  Because of this, the `SimpleCov.result?` check at the very beginning of `SimpleCov.process_result` will always return `true`, as `@result` was initialized by the preceding `SimpleCov.result` call:
https://github.com/colszowka/simplecov/blob/03a9f7fde44a9388580977e4002b4f6823c2b4cc/lib/simplecov.rb#L197-L224
Due to the misordering of the `.result` and `.result?` calls, any code that (like [`bashcov`](https://github.com/infertux/bashcov/blob/5d67802dabd01bd0996556b735c44f6622aa1c66/bin/bashcov#L22-L31)) stores results manually with `ResultMerger.store_result` will have its coverage data clobbered when `SimpleCov.result` calls …
> Don't call SimpleCov.result before checking SimpleCov.result?

- lib/simplecov/profiles/rails.rb
ActionCable is enabled in a default Rails project. (There may be few projects using ActionCable...)
In general, simplecov reads before Rails starts up, so ActionCable is not defined at this time.
That is, since the group in the ActionCable is not always true, I submitted this pull request.
> Delete condition for ActionCable group in Rails profile.

- CHANGELOG.md
- features/minimum_coverage.feature
- lib/simplecov.rb
My team uses SimpleCov at work. Thank you for the work. We have a Jenkins setup that runs specs using [parallel_tests](https://github.com/grosser/parallel_tests). 
Recently we  turned on `SimpleCov.minimum_coverage` and sometimes we started getting random failures. Eventually, we found out that it was because of the way minimum coverage is calculated, certain `parallel_tests` groupings had coverage below the minimum. We got final output like this: 
> 13752 examples, 0 failures, 120 pendings
> Tests have failed for a parallel_test group.
With parallel_tests and our Jenkins setup, the message about "expected minimum coverage..." wasn't at the end, so it's isn't clear. 
During the debugging process, I spent some time looking for words like `failed`, `failure`, `exit` to try to see if the …
> Explicitly print the exit status when SimpleCov fails the build

- doc/alternate-formatters.md
* Add documentation to a simplecov formatter that creates a small-badge similar to the one know from travis and friends (simplecov-small-badge).
* Based on SVG as a format.
> [Documentation] Feature/add simplecov-small-badge

- spec/simplecov_spec.rb
This is an error after merging 2 decent PRs that passed in
isolation but not when merged together :)
> process_result no longer relies on result? as order was changed

- Gemfile
Seems to have been broken during #705 but still worked on CI
cos it's in the different Gemfiles.
Hope this "fix" doesn't break anything else :)
> Include rubocop in the "default" gem

- CHANGELOG.md
- lib/simplecov/defaults.rb
- lib/simplecov/profiles/hidden_filter.rb
- spec/filters_spec.rb
It seems a bit weird, that hidden files and folders are included in the coverage measurement per default. They are hidden for a reason.
I now filter per default hidden folders and files in the root folder.
@colszowka do you have a strong opinion about that?
> Add filter for hidden files and folders per default

- README.md
Enabling eager loading will mean every test takes additional time to run.
Instead, we can disable Spring using an environment variable.
> Add an alternative way to work with Spring

- README.md
Make sure the Coverage link is pointing to the latest version instead of a hard coded version which will get stale overtime.
> Fix the Coverage Link

- CHANGELOG.md
- lib/simplecov/configuration.rb
- spec/configuration_spec.rb
I was trying something out, and I thought that it would be funny/useful to point this out to the user
> Warn the user if the minimum coverage is set greater than 100

- lib/simplecov.rb
`ParallelTests.last_process?` returns `true` if the process is the last one to start.  We are
interested in the last test to finish so we want to use `ParallelTests.number_of_running_processes`
Because it's possible to have the parallel_tests gem in your project and still run tests serially we
want to also check if tests are currently being run in parallel.  If `ENV['TEST_ENV_NUMBER']` is defined we know tests are currently being run in parallel.
> Avoid hanging with parallel_tests

- CHANGELOG.md
- README.md
- lib/simplecov.rb
- lib/simplecov/configuration.rb
- spec/configuration_spec.rb
- spec/fixtures/frameworks/rspec_bad.rb
- spec/fixtures/frameworks/testunit_bad.rb
- spec/helper.rb
- spec/return_codes_spec.rb
PR #688 added functionality that broke the
[`JacobEvelyn/friends`](https://github.com/JacobEvelyn/friends)
build (see https://travis-ci.com/JacobEvelyn/friends/jobs/238680478),
which runs many CLI processes and parses the output. Some CLI
processes are expected to have non-success status codes, but
these tests also check that our CLI wrote the correct message
to STDERR, and with #688 the output to STDERR is now changed.
This commit adds a SimpleCov configuration flag to disable the
message added in #688.
> Add option to disable error status code printing

- features/step_definitions/parameter_types.rb
- simplecov.gemspec
This removes the Transform deprecation warning:
```
WARNING: #Transform is deprecated and will be removed after version 3.0.0. 
Please follow the upgrade instructions at **https://cucumber.io/blog/2017/09/21/upgrading-to-cucumber-3.**
```
> Update cucumber to 3.x

- CHANGELOG.md
- lib/simplecov/command_guesser.rb
The camel-case constant `MiniTest` will be dropped in Minitest 6. It's been `Minitest` for a number of years now so this change should be fairly safe.
> Update references to Minitest constant

- .rubocop.yml
- Rakefile
- lib/simplecov.rb
- lib/simplecov/defaults.rb
- lib/simplecov/filter.rb
- lib/simplecov/formatter/multi_formatter.rb
- lib/simplecov/formatter/simple_formatter.rb
- lib/simplecov/result_merger.rb
- lib/simplecov/source_file.rb
- simplecov.gemspec
- spec/faked_project/features/support/env.rb
- spec/faked_project/lib/faked_project/some_class.rb
- spec/faked_project/spec/spec_helper.rb
- spec/faked_project/test/test_helper.rb
- spec/filters_spec.rb
- spec/fixtures/deleted_source_sample.rb
- spec/fixtures/utf-8.rb
- spec/lines_classifier_spec.rb
- spec/result_merger_spec.rb
- spec/simplecov_spec.rb
#754 introduced several problems in the rubocop setup:
* It updated the configuration to use `Style/TrailingCommaInArrayLiteral` and `Style/TrailingCommaInHashLiteral`. However, those cops [were introduced in rubocop 0.53.0](https://rubocop.readthedocs.io/en/latest/cops_style/#styletrailingcommainarrayliteral), and we're using rubocop 0.49.0.
* The code was changed to enforced exactly the opposite style being configured. The cops were setup to enforce a trailing comma at the end of hash and array literals, but the code was updated to remove that trailing comma.
The reason why the rubocop run is current passing is because the cops are not recognized in rubocop 0.49.0, and get ignored.
In this PR, I update the configuration of these cops to match the current style of the code, and also …
> Rubocop improvements

- README.md
Update indents in 'Getting Started' section so numbered list sections 4 & 5 are formatted correctly.
See:
https://github.com/MSP-Greg/simplecov/blob/readme-update/README.md
vs
https://github.com/colszowka/simplecov/blob/a162a42ca06b19c54eb02f6f4dc21946ba6cef33/README.md
> README.md - update 'Getting Started' [skip ci]

- .travis.yml
This PR bumps some software used in TravisCI, such as rubygems and the ruby versions we test against.
> Bump CI things

- Gemfile
- Gemfile.lock
- features/support/env.rb
Bump `capybara` to the latest version and replace `phantomjs` + `poltergeist` with [`apparition`](https://github.com/twalpole/apparition).
> Modernize test tools

- cucumber.yml
Fixes a couple of deprecations when running cucumber scenarios:
```
Deprecated: Found tags option '~@wip'. Support for '~@tag' will be removed from the next release of Cucumber. Please use 'not @tag' instead.
Deprecated: Found tags option '~@exclude-ruby'. Support for '~@tag' will be removed from the next release of Cucumber. Please use 'not @tag' instead
```
> Fix cucumber deprecations

- features/maximum_coverage_drop.feature
- features/minimum_coverage.feature
- features/refuse_coverage_drop.feature
- lib/simplecov.rb
- spec/simplecov_spec.rb
> Stricter coverage percentage computation to ensure 100% coverage means exactly 100%

- simplecov.gemspec
Add `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, and `source_code_uri` to the gemspec metadata.
These [project metadata](https://guides.rubygems.org/specification-reference/#metadata) will facilitate easy access to project information. The URI will be available on the [Rubygems project page](https://rubygems.org/gems/simplecov), via the rubygems API, and the `gem` and `bundle` command-line tools with the next release.
> Add project metadata to the gemspec

- features/support/env.rb
Couldn't reproduce locally.
As the failure was only ever JRuby, one test and the gif at that
(which shouldn't matter for the result of the test as a whole)
decided to just roll with it with an empty response and log
when it happens so that we could track other failures back to it.
fixes #776
> (Hopefully) fix #776 by returning empty responses on not found file

- features/support/env.rb
The timeout should already be correctly set in the Aruba.configure
block further down below.
> Remove unneeded exit timeout

- README.md
- lib/simplecov.rb
- lib/simplecov/configuration.rb
- spec/configuration_spec.rb
This is more flexible as it also accommodates for all the other
coverage types. It would also allow us to use an array like
`[:branch, :lines, :methods]` or something in the future.
It's also arguable a better name, let me know if you disagree :) Criteria is what wikipedia and other sources call/called it: https://en.wikipedia.org/wiki/Code_coverage
I'm also half-way sure that this will intermittently break
branch coverage but that's why adding an integration test there
is next on the list!
#781
> Change wording of branch coverage to coverage_criterion

- .rubocop.yml
- spec/fixtures/branches.rb
- spec/fixtures/coverer.rb
- spec/fixtures/inline.rb
- spec/source_file_spec.rb
This PR mainly takes the existing tests and makes the provided coverage data match the files that are being tested so that they are consistent and we have the actual files in the repo to work with them.
Also adds some new tests for some scenarios (as they were previously tested with files that didn't match what they were doing).
#781
> Tighten branch coverage tests & remove inconsistencies

- lib/simplecov.rb
- lib/simplecov/command_guesser.rb
- lib/simplecov/configuration.rb
- lib/simplecov/file_list.rb
- lib/simplecov/formatter/simple_formatter.rb
- lib/simplecov/profiles.rb
- lib/simplecov/result_merger.rb
lib/simplecov/command_guesser.rb
lib/simplecov/configuration.rb
lib/simplecov/file_list.rb
lib/simplecov/profiles.rb
lib/simplecov/result_merger.rb
lib/simplecov/formatter/simple_formatter.rb
In some doc systems, comments as below will be attached to module A:
```ruby
#
module A
class B
end
end
```
Moved inside `module A`:
```ruby 
module A
#
class B
end
end
```
> Move comments to attach to correct module/class [skip ci]

- README.md
- features/branch_coverage.feature
- lib/simplecov.rb
- lib/simplecov/configuration.rb
- spec/configuration_spec.rb
Branch coverage is best to accompany line coverage as branch
coverage itself has some gaping holes in it (namely that it
doesn't care about code without conditionals).
coverage_criterion will most likely evolve to be the "primary
coverage criterion" for the full release.
This API right now should be future proof but also easier.
#781
> Make activation of branch coverage more sensible

- CHANGELOG.md
Since we bumped the minimum required ruby version in the gemspec file, simplecov is no longer installable on older rubies. Not sure if the previous wording intended to say that you could fork the gem, manually edit the gemspec, and maybe get the gem to work on older rubies. In any case, I think it's better to say that you can no longer install the gem on those rubies.
> Clarify support drop changelog entry

- CHANGELOG.md
- lib/simplecov.rb
- lib/simplecov/configuration.rb
- spec/simplecov_spec.rb
when activating branch coverage before SimpleCov would also instruct Ruby to take Method coverage
#781
> Only turn on requested coverage criteria on the Ruby Coverage side

- Gemfile
- Gemfile.lock
- features/support/env.rb
```
$ bundle exec rake
Running RuboCop...
Inspecting 118 files
......................................................................................................................
118 files inspected, no offenses detected
/home/deivid/.rbenv/versions/2.7.0/bin/ruby -I/home/deivid/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.1/lib:/home/deivid/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-support-3.9.2/lib /home/deivid/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.1/exe/rspec spec/command_guesser_spec.rb spec/config_loader_spec.rb spec/configuration_spec.rb spec/defaults_spec.rb spec/deleted_source_spec.rb spec/file_list_spec.rb spec/filters_spec.rb spec/gemspec_spec.rb spec/last_run_spec.rb spec/lines_classifier_spec.rb …
```
> Avoid ruby 2.7 warnings during tests

- README.md
I often get asked by users of my knapsack_pro gem how to make simplecov working with my tool. I noticed you have a section for `Notes on specific frameworks and test utilities` so I've created this PR. Let me know if this looks ok.
Here is preview:
https://github.com/ArturT/simplecov/tree/note-knapsack#notes-on-specific-frameworks-and-test-utilities
> Add note how to use simplecov with knapsack_pro gem

- Gemfile
- Gemfile.lock
- features/support/aruba_bundler_run_command_fix.rb
- features/support/env.rb
I'd like to use aruba's master for our specs because I added [a change](https://github.com/cucumber/aruba/pull/675) that I'm finding useful when working with simplecov's cucumber scenarios.
I also removed an extension recently added to aruba, because otherwise specs won't run against aruba 1.0. I thought Aruba 1.0 was fixing the issues, but then I noticed that even without upgrading aruba, the scenarios will pass anwyays without the extension. So, I'm not sure why the aruba extension is needed.
> Use latest aruba

- lib/simplecov/source_file.rb
- spec/source_file_spec.rb
I "flip flopped" a lot on this, the initial PR had it implemented
as omitting this. You can make an argument either way.
You can say your case statement already handles the entire range
of input values given your domain. And then testing another
value seems too much as it's not realistic (or caught elsewhere).
However, who are we to hide additional branch coverage data
from users?
It's also more consistent as we also display the else branch
for if statement without an else. I also think it might help
show lapses in coverage.
```ruby
var =
case arg
when "functional"
55
when "something"
42
end
var += 1
```
When we never hit a branch we get an error down there, it's
something peple might reliably forget.
On top of that it's actually more code to ignore it.
So to summarize it why should we …
> Show missed else branch of case statements even if not declared

- Rakefile
- lib/simplecov.rb
- lib/simplecov/combine/files_combiner.rb
- lib/simplecov/combine/results_combiner.rb
- lib/simplecov/result.rb
- lib/simplecov/result_adapter.rb
- lib/simplecov/result_merger.rb
- lib/simplecov/simulate_coverage.rb
- lib/simplecov/source_file.rb
- lib/simplecov/useless_results_remover.rb
- spec/combine/results_combiner_spec.rb
- spec/file_list_spec.rb
- spec/helper.rb
- spec/result_merger_spec.rb
- spec/result_spec.rb
- spec/simplecov_spec.rb
- spec/source_file_spec.rb
- spec/useless_results_remover_spec.rb
A lot of them we convered back to strings anyhow, plus with
frozen string literal the gains are negligible anyhow.
Also, always symbolizing everything in the JSON.parse was a bit
of an overkill especially when you imagine a code base with lots
of files and lots of branches we could easily contribute to
blowing up memory considerably/beyond an accepatable threshhold.
> Stop generally symbolizing all the keys

- lib/simplecov/configuration.rb
Shouldn't change within one process. As we check the value
potentially a lot caching it can/would/should be nice as opposed
to a require (that should no op but needs to check) and getting
a method arity.
> Cache whether we're supporting branch coverage

- Gemfile
- Gemfile.lock
- features/branch_coverage.feature
- features/step_definitions/html_steps.rb
- lib/simplecov/source_file.rb
- lib/simplecov/source_file/branch.rb
- spec/source_file/branch_spec.rb
- spec/source_file_spec.rb
I believe this is much more user friendly as opposed to the
thinking what is positive/negative (like in an unless ... else,
or case when else). This way people see immediately that the else
branch was/wasn't hit or the then branch or the body of a loop.
Specifically I think it also helps with us reporting else branches
that aren't even defined (for if/case) - when people see 0 hits
for an else branch I think that's easier to figure out than
0 hits for the "-" branch. There's less of a "what does -/+ mean?"
going on.
As a side effect, also removes some code for checking what's
positive that's also rather intricately tied to how branch
coverage hands out its IDs which I don't believe we should take
for granted forever.
Old:
New:
> Let the HTML report show the branch type instead of +/-

- features/step_definitions/html_steps.rb
In the previous version we got the node and its text and then
did a manual check. The title might not have changed at that
time.
Using the special method we use capybara's built in waiting
capabilities and shouldn't be flaky anymore.
> Fix flaky by utilizing capybara waiting behaviour

- CHANGELOG.md
- features/old_version_json.feature
- features/step_definitions/old_coverage_json_steps.rb
- lib/simplecov/combine/results_combiner.rb
- lib/simplecov/result.rb
- spec/combine/results_combiner_spec.rb
- spec/result_spec.rb
After discussion with @deivid-rodriguez I realized that adapting
the result isn't actually that difficult and it's actually
a better solution to my current problem (that the warning
gets printed multiple times).
Yes, one could have moved the code around so that wrong format
results wouldn't even be written back, but Deivid was right
it might be useful for some people to keep the result and it's
actually not more complicated than sorting them out.
So this change fixes the multiple warnings as well as keeping
old results around.
Also moved the checking/changing to a fairly central place to
safeguard against old results flying in from somewhere else.
> Adapt old resultset.jsons instead of just warning

- README.md
Since I'm labeling the badge as "stable", I wanted to actually link to the "stable" workflow, which should always be green, while the other might not.
> Fix Github Actions badge link

- lib/simplecov.rb
- lib/simplecov/coverage_data.rb
- lib/simplecov/file_list.rb
- lib/simplecov/source_file.rb
- spec/coverage_data_spec.rb
- spec/file_list_spec.rb
- spec/source_file_spec.rb
The bigger purpose is multi step where the access to coverage data is normalized and hence methods that work with expecting a minimum amount of coverage and formatters can work with the known good same data base as opposed to memoizing all different method names.
This is good enough as an intermediate PR.
By virtue of unifying coverage computation we also get rid of inconsistencies like #565 
While I was there and happily modified things, I also got rid off inheriting from a core class (Array).
> Unify statistics computation and access to coverage data

- features/step_definitions/html_steps.rb
This is the flaky:
```
expected to find visible css ".header h3" with text "lib/faked_project/some_class.rb" but there were no matches. Also found "lib/faked_project/framework_specific.rb", "lib/faked_project/meta_magic.rb", "lib/faked_project/some_class.rb", "spec/forking_spec.rb", "spec/meta_magic_spec.rb", "spec/some_class_spec.rb", "lib/faked_project.rb", which matched the selector but not all filters.  (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/html_steps.rb:63:in `/^I open the detailed view for "(.+)"$/'
features/branch_coverage.feature:30:in `When I open the detailed view for "lib/faked_project/some_class.rb"'
Failing Scenarios:
cucumber features/branch_coverage.feature:6 # Scenario: 
```
Couldn't reproduce locally. As all steps before the one that …
> attempt at fixing flaky

- features/minimum_coverage.feature
- lib/simplecov.rb
- lib/simplecov/configuration.rb
- lib/simplecov/file_list.rb
- lib/simplecov/result.rb
- lib/simplecov/source_file.rb
- spec/configuration_spec.rb
- spec/simplecov_spec.rb
It's missing a feature test for usage with branch coverage and/or branch/line coverage combined (maybe also some unit tests but that exit code handling is kinda gnarly).
cc: @tycooon ;) I think for initial release it's just gonna be this one and we can add in minimum_coverage_by_file/maximum_coverage_drop etc. later
> Define minimum coverage by coverage criterion

- lib/simplecov/source_file.rb
- spec/fixtures/coverer.rb
- spec/fixtures/single_nocov.rb
- spec/fixtures/uneven_nocovs.rb
- spec/source_file_spec.rb
Fixes #846
We just assume them to go until the end. Test against a full nocov
for the file as well as a small mixture.
If this passes on CI I'll cut a new bugfix release.
cc: @DannyBen
> Fix crashes with uneven number of nocov instructions

- lib/simplecov/combine.rb
- lib/simplecov/combine/branches_combiner.rb
- lib/simplecov/coverage_statistics.rb
- spec/configuration_spec.rb
- spec/coverage_statistics_spec.rb
- spec/fixtures/skipped_and_executed.rb
- spec/simplecov_spec.rb
- spec/source_file_spec.rb
- test_projects/faked_project/spec/meta_magic_spec.rb
Simple refactor of `SimpleCov::CoverageStatistics` that makes the code slightly more efficient and readable. Also fixes a spec (along with some clean up).
I also searched for typos using [cspell](https://www.npmjs.com/package/cspell). I manually fixed the obvious typos that were reported (and ignored tons of false positive matches).
> Refactor CoverageStatistics class & specs and fix typos

- CHANGELOG.md
I didn't add this information as to my mind we didn't change any API documented anywhere and hence it shouldn't appear in a Changelog.
However, this affects people and they have to find out for themselves so notifying them of this might be a good thing. I still couldn't bring myself to put it under breaking changes as technically we haven't broken anything that we ever communicated as working.
So a link to https://github.com/codeclimate/test-reporter/issues/413 seems to be helpful.
> Amend 0.18 changelog with notice about code climate test reporter

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- features/minitest_basic.feature
- features/step_definitions/simplecov_steps.rb
- lib/minitest/simplecov_plugin.rb
- lib/simplecov.rb
- lib/simplecov/defaults.rb
- test_projects/faked_project/Rakefile
- test_projects/faked_project/minitest/other_test.rb
- test_projects/faked_project/minitest/some_test.rb
- test_projects/faked_project/minitest/test_helper.rb
This is me trying to resurrect #756
> Rebase: Fix at_exit hook to cooperate with Minitest

- .rubocop.yml
- Gemfile
- Gemfile.lock
- features/encoding.feature
- features/step_definitions/html_steps.rb
- features/step_definitions/web_steps.rb
- lib/simplecov/source_file.rb
- spec/fixtures/euc-jp-shebang.rb
- spec/fixtures/euc-jp.rb
- spec/fixtures/utf-8-magic.rb
- spec/source_file_spec.rb
- test_projects/encodings/lib/euc_jp.rb
- test_projects/encodings/lib/euc_jp_not_declared.rb
- test_projects/encodings/lib/euc_jp_not_declared_tracked.rb
- test_projects/encodings/lib/utf8.rb
- test_projects/encodings/spec/simple_spec.rb
- test_projects/encodings/spec/spec_helper.rb
Based on #865 
I had a bit of trouble grasping the solution, so needed to play with myself and add some more tests to make sure nothing does/did explode.
Still probably want to add one acceptance test to make sure the html formatter doesn't blow it up for some reason.
> Convert utf8

- features/minitest_basic.feature
- lib/minitest/simplecov_plugin.rb
- simplecov.gemspec
* Fixes #877
* not quire sure whether we should wrap the entire thing in
if undefined?(..) or not but since the file has all the right
structure otherwise I'm more worried about minitest being
weirded out that it doesn't find what it expects than I am
of letting it execute an empty method
* also yes the version workaround is maybe a bit weird, however
I wanted our test suite to reproduce the exact failure case
because otherwise it'd be to easy to just implement a
respond_to? check which would have everything passing but would
fail in real life.
> Only run our minitest plugin code if SimpleCov is indeed defined

- CHANGELOG.md
- README.md
- features/config_enable_for_subprocesses.feature
- features/support/env.rb
- lib/simplecov.rb
- lib/simplecov/configuration.rb
- lib/simplecov/process.rb
- spec/simplecov_spec.rb
- test_projects/subprocesses/.simplecov
- test_projects/subprocesses/.simplecov_spawn.rb
- test_projects/subprocesses/lib/command
- test_projects/subprocesses/lib/subprocesses.rb
- test_projects/subprocesses/spec/simple_spec.rb
- test_projects/subprocesses/spec/spawn_spec.rb
- test_projects/subprocesses/spec/spec_helper.rb
Using Process.fork (whether using the Parallel gem or directly)
creates code that was invisible to SimpleCov. by starting SimpleCov
within the subprocess with its own command name and etc we can
see that code :)
This also adds documentation for what to do when using Process.spawn or
similar.
fixes: #414 and probably others
---
This seems the more correct place to fix this than my previous attempt here: https://github.com/grosser/parallel/issues/275
Testing was a bit of a mess, perhaps you have some ideas, 
Also what are your thoughts on this being enabled by default or not?
Thanks :)
> Add subprocess handling to simplecov

- features/config_root.feature
- lib/simplecov/useless_results_remover.rb
- test_projects/monorepo/Gemfile
- test_projects/monorepo/Gemfile.lock
- test_projects/monorepo/base/base.gemspec
- test_projects/monorepo/base/lib/monorepo/base.rb
- test_projects/monorepo/bin/rspec_binstub_that_chdirs
- test_projects/monorepo/extra/extra.gemspec
- test_projects/monorepo/extra/lib/monorepo/extra.rb
- test_projects/monorepo/extra/spec/extra_spec.rb
- test_projects/monorepo/extra/spec/spec_helper.rb
If user configures a custom `SimpleCov.root`, results outside of the new root wouldn't be properly filtered out since the regexp for filtering was being set at require time, before the `SimpleCov.root` configuration had been applied.
Instead, lazily set this regexp, so that by the time it is used, the new `SimpleCov.root` value is already setup.
Fixes #885.
> Fix regexp for filtering out non-root results being set too early

- .github/workflows/unstable.yml
I think this is better because:
* We get faster feedback for PRs.
* We get less hidden failures under then "Actions" tab, instead of having them hidden under a green check on PRs.
Thoughts?
> Run unstable workflow daily

- lib/simplecov/filter.rb
Just saw that while checking up on filters.
Thanks for the great work!
> Add missing quote to example in comments

- CHANGELOG.md
- features/parallel_tests.feature
- features/rspec_failing.feature
- lib/simplecov.rb
- lib/simplecov/exit_codes.rb
- lib/simplecov/exit_codes/exit_code_handling.rb
- lib/simplecov/exit_codes/maximum_coverage_drop_check.rb
- lib/simplecov/exit_codes/minimum_coverage_by_file_check.rb
- lib/simplecov/exit_codes/minimum_overall_coverage_check.rb
- spec/return_codes_spec.rb
- spec/simplecov_spec.rb
- test_projects/faked_project/bad_spec/fail_with_5.rb
- test_projects/faked_project/bad_spec/failing_spec.rb
- test_projects/faked_project/bad_spec/spec_helper.rb
- test_projects/parallel_tests/Gemfile.lock
Basically a semi precursor to reviving #739 as I didn't want to meddle with this code. 
Individual commits have more information.
> Exit status refactoring & differentiate originator of failign exit code

- CHANGELOG.md
- features/parallel_tests.feature
- lib/simplecov.rb
As we found out ParallelTests isn't necessarily always available.
Hence the new require logic.
Also added a different mechanism for waiting that should get
rid off at least one race condition.
I just managed to run the parallel_test tests without fail
for 50 times. I had a failure before so we'll see how robust
these are on CI.
Ref: https://github.com/grosser/parallel_tests/issues/772#issuecomment-672010347
Code probably still needs some work and restructuring as when
does "result" get called and the waiting is definitely somewhat
flaky.
> Make ParallelTests available and change waiting mechanism

- lib/simplecov.rb
- lib/simplecov/result.rb
- lib/simplecov/result_merger.rb
- spec/result_spec.rb
Inspired by #687
This feels cleaner as we have one centralized instead of 2
things making up their own loop leaking knowledge about the
data structure. That knowledge is now more contained in the
Result class which is great.
Using select also feels much better.
If anyone was using Result.from_hash we might break their code
as it's an Array now. I hope not/nobody should :)
> Change Result#from_hash to deal with many entries isntead one

- lib/simplecov.rb
Monkey patching `Process.fork` causes issues with applications that make use of fork but also run on Ruby builds without fork (like Windows & JRuby).
Fix so `./simplecov/process.rb` is only required if the platform supports `Process.fork`.
> simplecov.rb - fix Process monkey patch for fork when unsupported

- benchmarks/result.rb
The only benchmark got accidentally broken when all the test projects were moved from `./spec/test_projects` to `./test_projects` in https://github.com/simplecov-ruby/simplecov/pull/814. This PR fixes it.
Before:
```
➜  simplecov git:(main) ruby benchmarks/result.rb
Traceback (most recent call last):
1: from benchmarks/result.rb:9:in `<main>'
benchmarks/result.rb:9:in `require_relative': cannot load such file -- /Users/dnnx/work/simplecov/spec/faked_project/lib/faked_project (LoadError)
```
After:
```
➜  simplecov git:(fix-benchmarks) ruby benchmarks/result.rb
Warming up --------------------------------------
generating a simplecov result
7.000  i/100ms
Calculating -------------------------------------
generating a simplecov result
78.386  (± 1.3%) i/s -    392.000  in   5.002603s
```
Can …
> Fix the benchmark

- doc/alternate-formatters.md
I created a new formatter with Tailwind and looking to add to the Docs for available formatters to leverage.
Thanks!
> Add simplecov tailwindcss formatter to docs

- features/skipping_code_blocks_manually.feature
- features/step_definitions/html_steps.rb
As we're first querying the visible files and then comparing
the expected counts we're not making use of capybaras waiting
in case they're not loaded yet. This change embeds the expectation
in the query making use of the patient waiting and functioning
as an expectation at the same time.
#925
> Remove flakyness from see source files step

- features/warnings.feature
- lib/simplecov/configuration.rb
- spec/configuration_spec.rb
>  Prevent an "instance variable not initialized" warning

- lib/simplecov/configuration.rb
As updating `coverage_dir`, updating `root` should invalidate `coverage_path` cache.
> Invalidate coverage_path cache for updating root

- lib/simplecov/lines_classifier.rb
- lib/simplecov/source_file/line.rb
This PR aims to improve performance of SimpleCov a bit.
See individual commits message for more details.
```
$ ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
```
```ruby
require "benchmark/ips"
class Foo
attr_reader :skipped
def initialized
@skipped = false
end
def skipped?
!!skipped
end
def skipped2?
skipped
end
end
foo = Foo.new
Benchmark.ips do |x|
x.report "old" do
foo.skipped?
end
x.report "new" do
foo.skipped2?
end
x.compare!
end
#
```
```ruby
require "benchmark/ips"
string = "ok"
regexp = /ok/
Benchmark.ips do |x|
x.report "old" do
string =~ regexp
end
x.report "new" do
regexp.match?(string)
end
x.compare!
end
#
```
> Minor performance improvements

- CHANGELOG.md
- README.md
- features/maximum_coverage_drop.feature
- features/refuse_coverage_drop.feature
- lib/simplecov.rb
- lib/simplecov/configuration.rb
- lib/simplecov/exit_codes/maximum_coverage_drop_check.rb
- lib/simplecov/exit_codes/minimum_coverage_by_file_check.rb
- lib/simplecov/file_list.rb
- lib/simplecov/result.rb
- spec/configuration_spec.rb
This implements branch coverage support for `:minimum_coverage_by_file`, `:maximum_coverage_drop`, and `:refuse_coverage_drop`. 
Resolves Issue #844.
> Implement branch coverage support for exit status modifiers

- CHANGELOG.md
- README.md
- features/maximum_coverage_drop.feature
- features/minimum_coverage.feature
- lib/simplecov/configuration.rb
- spec/configuration_spec.rb
This implements #843 to create a `primary_coverage` option, and allows you to set primary coverage to branch. Primary coverage will come first in output, and also will be the default if coverage type is not specified in custom exit behavior.
> Allows switching primary coverage to something other than line

- .rubocop.yml
- lib/simplecov.rb
- lib/simplecov/configuration.rb
- lib/simplecov/result.rb
- lib/simplecov/result_merger.rb
- spec/fixtures/conditionally_loaded_1.rb
- spec/fixtures/conditionally_loaded_2.rb
- spec/fixtures/parallel_tests.rb
- spec/helper.rb
- spec/result_merger_spec.rb
- spec/result_spec.rb
- spec/simplecov_spec.rb
Draft to get early feedback! (cc: @deivid-rodriguez ? :D ) So Todos and fixmes are intended and will either get resolved or turned into tickets.
I'm worried about breaking things, as the work to move my [quick performance hack](https://github.com/simplecov-ruby/simplecov/compare/collate-plus-plus?expand=1) to main line code was more involved than I had hoped.
I haven't measured this again but memory consumption and speed gains were massive with the initial spike. Perf was ~2x for my smaller sample set and it allowed the big sample set to do its thing at all (I killed it at 12GB memory consumption).
------------------------------------------------------
We used to read all files into memory - which gets too much if
someone runs a massively parallel CI because 400 * 10MB is still
~4GB and …
> Improve performance of collate & reduce memorty consumption

- CHANGELOG.md
- Gemfile.lock
- features/minimum_coverage_by_file.feature
- lib/simplecov/exit_codes/minimum_coverage_by_file_check.rb
- lib/simplecov/file_list.rb
- lib/simplecov/version.rb
- spec/exit_codes/minimum_coverage_by_file_check_spec.rb
minimum_coverage_by_file was a gaping hole in the test suite,
which is now partially remedied through rather thorough cucumber
scenarios and 2 small unit tests that should be expanded on in
the future.
On the negative side: This will inconvenince some people. On the
positive side stuffed another hole in the test suite towards a
better future :D Also it was reported very soon thanks to @iMacTia
Fixes #965
> Fix minimum_coverage_by_file check & prep 0.21.1

- Gemfile.lock
I'm semi sure the bug was introduced by bundler upgrade, but
`bundler update pry` then removed the pry-java version but
everything still seems to be working so... :shrug:
Errornous build: https://github.com/simplecov-ruby/simplecov/pull/972/checks?check_run_id=1841431350
PR in which this occured: #972
> Fix error in jruby CI job via gem upgrades

- README.md
We got confused when trying to use the CSVFormatter and discovered it also required another gem (at least for our version). Thus I suggest adding a clarification as I suggest in this PR. It might also be more clear if the "Multiple formatters" heading was below the "JSON formatter" section.
> Add needed require line for CSV example

- README.md
Both bash and cmd do not require quotes around echo statements
Unify the command to add simplicity to README
> Unify windows and bash .gitignore addition

- Gemfile
- Gemfile.lock
This avoids unnecessary warnings in the test output.
See https://github.com/twalpole/apparition/pull/79
> test: Use unreleased version of apparition

- lib/simplecov/source_file.rb
It was tested on `rubocop`s codebase.
```
▶ pwd
/Users/fatkodima/Desktop/oss/rubocop
▶ cloc --include-lang=Ruby .
1555 text files.
1555 unique files.
235 files ignored.
github.com/AlDanial/cloc v 1.90  T=1.75 s (757.4 files/s, 122769.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Ruby                          1323          30786          24683         158986
-------------------------------------------------------------------------------
SUM:                          1323          30786          24683         158986
--------------------------------------------------------------------------- …
```
> Reduce memory usage while generating report

- .gitignore
- README.md
- lib/simplecov.rb
- lib/simplecov/configuration.rb
- spec/coverage_for_eval_spec.rb
- spec/fixtures/eval_test/eval_test.erb
- spec/fixtures/eval_test/eval_test.rb
Since Ruby 3.2, coverage.so can measure coverage of code that evaluated by `Kernel#eval`. Typically, this would be useful for ERB.
https://bugs.ruby-lang.org/issues/19008
This change adds a new API for SimpleCov to enable the feature.
```ruby
SimpleCov.start do
enable_coverage_for_eval
end
```
Here is a sample output:
I hope this feature will be released until the release date of Ruby 3.2 (25th in this month).
> Support coverage for eval

- Gemfile.lock
Rack 2.2.3 suffers from 2 CVEs which are fixed in 2.2.3.1: 
https://github.com/rack/rack/blob/main/CHANGELOG.md#2231---2022-05-27
Signed-off-by: Theo Truong <theotr@amazon.com>
> [Security] Bumped Rack version to 2.2.3.1

- CHANGELOG.md
- Gemfile.lock
- features/minitest_basic.feature
- lib/simplecov/version.rb
- test_projects/monorepo/Gemfile.lock
- test_projects/parallel_tests/Gemfile.lock
- test_projects/rails/rspec_rails/Gemfile.lock
Contains most notably #1035 and #1037, as well as a number of tweaks to rubocop + gitlab actions changes
> Bump version to 0.22.0, update changelog

- Gemfile
I uncommented https://github.com/simplecov-ruby/simplecov/blob/v0.21.2/Gemfile#L6 to run test with local copy of simplecov-html ([currently main branch](https://github.com/simplecov-ruby/simplecov-html/tree/5bc5798aefed312abd189baed8a97bf1febfa8d7)).
I saw following:
```
yuya@yoshiyuki|12:09:34|0% bundle
...
yuya@yoshiyuki|12:09:47|0% bundle exec rake
...
Inspecting 108 files
C...........................................................................................................
Offenses:
Gemfile:6:29: C: [Correctable] Style/StringConcatenation: Prefer string interpolation to string concatenation.
gem "simplecov-html", path: File.dirname(__FILE__) + "/../simplecov-html"
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
108 files inspected, 1 offense detected, 1 offense auto-correctable …
```
> Fix incorrect comment on "Gemfile"

- .github/workflows/stable.yml
- .github/workflows/unstable.yml
- spec/return_codes_spec.rb
Fixes https://github.com/simplecov-ruby/simplecov/issues/1044.
@amatsuda Could you review and merge this?
> Add TruffleRuby in CI

- lib/simplecov.rb
Amends https://github.com/simplecov-ruby/simplecov/pull/1035/commits/1cc7650454fc7c53e7a724941662c3e9d3329ccc from #1035
Another option would be to just call Coverage.start unconditionally and rescue the RuntimeError it now raises when already started.
> allow Coverage to start when Coverage.running? is not implemented

- .github/workflows/stable.yml
- .github/workflows/unstable.yml
- Rakefile
No need to keep running rubocop, can esp. even be a bit slow on JRuby
> Run Rubocop only once in CI

- spec/return_codes_spec.rb
Follow-up for https://github.com/oracle/truffleruby/issues/3535.
Enables a test case in `spec/return_codes_spec.rb` file on `truffleruby-head`.
> Unexclude skipped on TruffleRuby test case

- .github/workflows/stable.yml
- .rubocop.yml
- README.md
- features/support/env.rb
- lib/simplecov/lines_classifier.rb
- lib/simplecov/source_file.rb
- simplecov.gemspec
This PR brings Ruby 2.7 back to the CI matrix by monkey-patching Capybara to correctly switch three `all` methods defined by Capybara, RSpec, and Aruba.
See https://github.com/teamcapybara/capybara/pull/2771 for the details of the Capybara patch.
> Bring Ruby 2.7 support back

- lib/simplecov/formatter/simple_formatter.rb
- spec/coverage_for_eval_spec.rb
Use `floor(2)` rather than `round(2)` as we do elsewhere across `Simplcov`
Follow up and relates to:
* https://github.com/simplecov-ruby/simplecov/pull/773/
Relates to and possibly helps with:
* https://github.com/simplecov-ruby/simplecov/issues/1115
> Follow the repo convention to use `floor` instead of `round` to provide actionable coverage metrics

- Gemfile
- Gemfile.lock
- test_projects/rails/rspec_rails/Gemfile
- test_projects/rails/rspec_rails/config/application.rb
- it is not loaded anymore as a side-effect of ruby-concurrent
- fix is included in Rails 7.0, but test app is still Rails 6.1 (https://github.com/rails/rails/pull/54264)
- lock RuboCop on CI, new cops are not compatible yet with current codebase
> Add logger to deps and load in early in test Rails app.
